import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { Navbar } from "./_components/navbar";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${geist.variable}`}>
			<body>
				<TRPCReactProvider>
					<div className="flex w-full flex-col sm:h-auto md:h-screen">
						<div className="-z-20 fixed h-full w-full bg-slate-800 " />
						<div
							className={"-z-10 fixed inset-0 h-full w-full bg-[url(/img/grid.svg)] bg-center [mask-image:radial-gradient(rgba(241,245,249,0.1),rgba(148,163,184,1));]"}
						/>
						<Navbar />

						<div className="container mx-auto h-full w-full">
							<div className="h-full w-full p-4">{children}</div>
							{/* <Toaster /> */}
						</div>
					</div>
				</TRPCReactProvider>
			</body>
		</html>
	);
}
